pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        timeout(time: 20, unit: 'MINUTES')
    }
    stages {
        stage('E2E') {
            steps {
                sh "echo 'Running E2E Test...'"
            }
        }
        stage('Reporting') {
            steps {
                sh "echo 'Publishing E2E Report...'"
            }
        }
    }
}